version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    container_name: foodgram-back
    build: ../backend/
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    build: ../frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/frontend_static

  gateway:
    depends_on:
      - backend
      - frontend
    container_name: foodgram-proxy
    build: ../gateway/
    ports:
      - "80:80"
    volumes:
      - media:/app/media
      - static:/staticfiles
